#!/usr/bin/env bash
# Script that displays the subdomain record

function get_subdomain_info {
  local domain=$1
  local subdomain=$2
  local full_domain="${subdomain}.${domain}"

  local result=$(dig +noall +answer ${full_domain} | awk '{print $4, $5}')
  local record_type=$(echo $result | awk '{print $1}')
  local ip_address=$(echo $result | awk '{print $2}')

  echo "The subdomain ${subdomain} is a ${record_type} record and points to ${ip_address}"
}
 
domain=$1
subdomain=$2

if [[ -z "$subdomain" ]]; then
  for sub in www lb-01 web-01 web-02; do
    get_subdomain_info $domain $sub
  done
else
  get_subdomain_info "$domain" "$subdomain"
fi
